In [20]:
from tensorflow.keras.preprocessing.text import one_hot

In [25]:
# sentence
sent = {    'the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'I am a good boy',
        'I m  good developer',
        'understand the meaninag of words',
        'your video are good'
}

In [36]:
print(sent)

{'the cup of tea', 'I m  good developer', 'understand the meaninag of words', 'I am a good boy', 'the glass of juice', 'your video are good', 'the glass of milk'}


In [23]:
# define the vocabulary size 
voc_size= 10000


In [24]:
# one hot representation
one_hot_rept=[one_hot(words,voc_size)for words in sent]
one_hot_rept

[[864, 3390, 8664, 7870],
 [1442, 8540, 1263, 2871],
 [6689, 864, 1404, 8664, 5471],
 [1442, 4438, 5877, 1263, 7934],
 [864, 1070, 8664, 2555],
 [8436, 4546, 3497, 1263],
 [864, 1070, 8664, 9866]]

In [30]:
# word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
# from tensorflow.keras.preprocessing import pad_sequences
from tensorflow.keras.models import Sequential


In [ ]:
import numpy as np

In [35]:
sent_length = 8
embedded_docs=pad_sequences(one_hot_rept,padding='pre',maxlen=sent_length)
print(embedded_docs)


[[   0    0    0    0  864 3390 8664 7870]
 [   0    0    0    0 1442 8540 1263 2871]
 [   0    0    0 6689  864 1404 8664 5471]
 [   0    0    0 1442 4438 5877 1263 7934]
 [   0    0    0    0  864 1070 8664 2555]
 [   0    0    0    0 8436 4546 3497 1263]
 [   0    0    0    0  864 1070 8664 9866]]


In [37]:
# feature representation
dim  =10


In [39]:
model= Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [40]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [41]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 305ms/step


array([[[-1.20429024e-02,  2.00312398e-02,  4.88290302e-02,
         -3.64615805e-02, -1.84116848e-02,  3.03720348e-02,
         -1.35270841e-02, -4.76042032e-02, -1.50400177e-02,
         -2.24114060e-02],
        [-1.20429024e-02,  2.00312398e-02,  4.88290302e-02,
         -3.64615805e-02, -1.84116848e-02,  3.03720348e-02,
         -1.35270841e-02, -4.76042032e-02, -1.50400177e-02,
         -2.24114060e-02],
        [-1.20429024e-02,  2.00312398e-02,  4.88290302e-02,
         -3.64615805e-02, -1.84116848e-02,  3.03720348e-02,
         -1.35270841e-02, -4.76042032e-02, -1.50400177e-02,
         -2.24114060e-02],
        [-1.20429024e-02,  2.00312398e-02,  4.88290302e-02,
         -3.64615805e-02, -1.84116848e-02,  3.03720348e-02,
         -1.35270841e-02, -4.76042032e-02, -1.50400177e-02,
         -2.24114060e-02],
        [-3.36703882e-02,  1.46708824e-02, -3.29507217e-02,
          4.65662368e-02,  3.70487459e-02, -4.57620025e-02,
          4.69588526e-02, -3.71580832e-02, -2.825530

In [42]:
embedded_docs[0]

array([   0,    0,    0,    0,  864, 3390, 8664, 7870])

In [43]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 72ms/step


array([[-0.0120429 ,  0.02003124,  0.04882903, -0.03646158, -0.01841168,
         0.03037203, -0.01352708, -0.0476042 , -0.01504002, -0.02241141],
       [-0.0120429 ,  0.02003124,  0.04882903, -0.03646158, -0.01841168,
         0.03037203, -0.01352708, -0.0476042 , -0.01504002, -0.02241141],
       [-0.0120429 ,  0.02003124,  0.04882903, -0.03646158, -0.01841168,
         0.03037203, -0.01352708, -0.0476042 , -0.01504002, -0.02241141],
       [-0.0120429 ,  0.02003124,  0.04882903, -0.03646158, -0.01841168,
         0.03037203, -0.01352708, -0.0476042 , -0.01504002, -0.02241141],
       [-0.03367039,  0.01467088, -0.03295072,  0.04656624,  0.03704875,
        -0.045762  ,  0.04695885, -0.03715808, -0.02825531, -0.03363788],
       [-0.00623636,  0.01348115, -0.02863468,  0.02090393,  0.01848287,
        -0.02794617, -0.03669459,  0.01744826,  0.02079793,  0.03350147],
       [ 0.03222365,  0.03806779, -0.02575389, -0.01535535,  0.01437372,
         0.04359877, -0.01390006,  0.03870488